### ISSUE TITLE
Next.js suggests to use `sharp` package for Image Optimization

### ISSUE THREAD

**Issue by shuwnyuantee** [Hivekind/hivekind.com#150]
Running `npm run build`, we see this suggestion from Next.js:
 
```
⚠ For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'npm i sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
```

**Comment by parasquid** [comment]
@shuwnyuantee i can't seem to find this message in the build logs:
- cloudflare https://dash.cloudflare.com/2244965ae1022ebf18ff2ef4f8db1b8a/pages/view/hivekind-com/556aa848-7433-4d91-bef5-bc5fec6bc870
- netlify https://app.netlify.com/sites/hivekind-com/deploys/6708b3e45f53b30008488fe5

**Comment by shuwnyuantee** [comment]
Running `npm run build` again today, and the message is no longer there. 
So we are closing this ticket with `won't fix`.
